var fs = require('fs');
require('dotenv').config();
var cloudinary = require('cloudinary').v2;

// File upload
async function UploadImageByCloudinary(imgData){
  console.log(imgData);
  try{
    const image = await cloudinary.uploader.upload(imgData);
      // console.log();
      // console.log("** File Upload");
      // console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
      // console.log("* " + image.public_id);
      // console.log("* " + image.url);
      // waitForAllUploads("pizza", err, image);
      return image.url;
  }
  catch(err){
    console.log(err);
  };
}

// UploadImageByCloudinary("aquaman.jpg");


module.exports = {UploadImageByCloudinary:UploadImageByCloudinary};