//Images
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_ERROR = "GET_IMAGES_ERROR";
export const UPLOAD_IMAGES_SUCCESS = "UPLOAD_IMAGES_SUCCESS";
export const UPLOAD_IMAGES_ERROR = "UPLOAD_IMAGES_ERROR";



//Authentication
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNOUT = "SIGNOUT";
export const UPLOAD_USER_IMAGE_SUCCESS = "UPLOAD_USER_IMAGE_SUCCESS";
export const UPLOAD_USER_IMAGE_ERROR = "UPLOAD_USER_IMAGE_ERROR";

//genre
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_ERROR = "GET_GENRES_ERROR";
export const DOWNLOAD_GENRES_SUCCESS = "DOWNLOAD_GENRES_SUCCESS";
export const DOWNLOAD_GENRES_ERROR = "DOWNLOAD_GENRES_ERROR";
export const GET_ALL_GENRES_SUCCESS = "GET_ALL_GENRES_SUCCESS"; 
export const GET_ALL_GENRES_ERROR = "GET_ALL_GENRES_ERROR";



//OTP
export const GET_OTP_SUCCESS = "GET_OTP_SUCCESS";
export const GET_OTP_ERROR = "GET_OTP_ERROR";


//UserDetail
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const GET_USER_DETAIL_ERROR = "GET_USER_DETAIL_ERROR";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";
export const FORGOT_VERIFY_SUCCESS = "FORGOT_VERIFY_SUCCESS";
export const FORGOT_VERIFY_ERROR = "FORGOT_VERIFY_ERROR";
export const FORGOT_UPDATE_SUCCESS = "FORGOT_UPDATE_SUCCESS";
export const FORGOT_UPDATE_ERROR = "FORGOT_UPDATE_ERROR";

//Loading
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SHOW_PAGE_LOADER = "SHOW_PAGE_LOADER";
export const HIDE_PAGE_LOADER = "HIDE_PAGE_LOADER";